# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 350b9bfc25f029350c480c8d469805b06c6df8202edd0162aaebd2561fda3fa04acc58fa9590cdbb3a76a7b81808757431db0705751c6de694bb0839a305a1d7

test:
  secret_key_base: c714d54f86400aab2ce888e8ca9b5e6442fbbb7792e98d8c087b8bae9cb85ac60f02165d414c05cf47083afd1451a13896b961450a748a9da84630af4d842867

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
